# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_assignment.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FIR_Direct_Form_IV_0_0/design_1_FIR_Direct_Form_IV_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FIR_Direct_Form_IV_0_0 || ORIG_REF_NAME==design_1_FIR_Direct_Form_IV_0_0} -quiet] -quiet

# XDC: c:/Users/USER/Documents/Vivado_pro/Session_3/FIR Fileter Pipeline/project_FIR/project_2.gen/sources_1/bd/design_1/design_1_ooc.xdc
